package qianfeng.qqmusicbymyself.showmusic.model.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import qianfeng.qqmusicbymyself.showmusic.model.bean.MusicBean;
import qianfeng.qqmusicbymyself.util.dbutil.UserSearchHistory;

import qianfeng.qqmusicbymyself.showmusic.model.bean.MusicBeanDao;
import qianfeng.qqmusicbymyself.util.dbutil.UserSearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicBeanDaoConfig;
    private final DaoConfig userSearchHistoryDaoConfig;

    private final MusicBeanDao musicBeanDao;
    private final UserSearchHistoryDao userSearchHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicBeanDaoConfig = daoConfigMap.get(MusicBeanDao.class).clone();
        musicBeanDaoConfig.initIdentityScope(type);

        userSearchHistoryDaoConfig = daoConfigMap.get(UserSearchHistoryDao.class).clone();
        userSearchHistoryDaoConfig.initIdentityScope(type);

        musicBeanDao = new MusicBeanDao(musicBeanDaoConfig, this);
        userSearchHistoryDao = new UserSearchHistoryDao(userSearchHistoryDaoConfig, this);

        registerDao(MusicBean.class, musicBeanDao);
        registerDao(UserSearchHistory.class, userSearchHistoryDao);
    }
    
    public void clear() {
        musicBeanDaoConfig.clearIdentityScope();
        userSearchHistoryDaoConfig.clearIdentityScope();
    }

    public MusicBeanDao getMusicBeanDao() {
        return musicBeanDao;
    }

    public UserSearchHistoryDao getUserSearchHistoryDao() {
        return userSearchHistoryDao;
    }

}
